### ISSUE TITLE
util: error on `make start` on M1 macbook

### ISSUE THREAD

**Issue by danaxd** [open-education-hub/operating-systems#186]
I have pulled the latest commit :  b6a0cbdff828bdabfb7403a597e325c747e6bfbe and I m facing some problems when running the following command: make start, following the instructions from the os-runner README.
I'm running this on an M1 macbook air.

This is the error message that I get:
```
make start
Error response from daemon: No such container: os-runner
docker buildx build --platform linux/amd64 -t "os-runner-image:b027eb3ab2bdfed1b017701bc0e4eafd10cb11ea" .
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x39 pc=0x101a21a00]

goroutine 1 [running]:
github.com/docker/buildx/builder.(*Builder).Validate(0x102c368a0?)
	github.com/docker/buildx/builder/builder.go:111 +0x20
github.com/docker/buildx/builder.New({0x102c368a0?, 0x140000d4400}, {0x1400063f450, 0x2, 0x100010000?})
	github.com/docker/buildx/builder/builder.go:101 +0x290
github.com/docker/buildx/commands.runBuild({_, _}, {{0x16ef8fa46, 0x1}, {0x0, 0x0}, {0x0, 0x0}, {0x103bab588, 0x0, ...}, ...})
	github.com/docker/buildx/commands/build.go:259 +0xedc
github.com/docker/buildx/commands.buildCmd.func1(0x140001e3500?, {0x140004b70e0?, 0x5?, 0x5?})
	github.com/docker/buildx/commands/build.go:461 +0xd0
github.com/spf13/cobra.(*Command).execute(0x140001e3500, {0x14000229a60, 0x5, 0x5})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x14000584900)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
github.com/docker/cli/cli-plugins/plugin.RunPlugin(0x1023778e9?, 0x140001e3200, {{0x102375b36, 0x5}, {0x10237fbfc, 0xb}, {0x1026bd958, 0x7}, {0x0, 0x0}, ...})
	github.com/docker/cli@v23.0.0-rc.1+incompatible/cli-plugins/plugin/plugin.go:51 +0x154
main.runPlugin(0x1023b940f?)
	github.com/docker/buildx/cmd/buildx/main.go:45 +0xcc
main.main()
	github.com/docker/buildx/cmd/buildx/main.go:62 +0xe0
make: *** [docker-image] Error 2
```

**Comment by Alex-deVis** [comment]
@gabrielmocanu, @edi33416, @darius-m, @doringeman, do you have any idea what might cause this?
B

**Comment by gabrielmocanu** [comment]
Hi @danaxd 

Can you provide your docker engine version?

`docker --version`

**Comment by danaxd** [comment]
Docker version 23.0.1, build a5ee5b1dfc

**Comment by danaxd** [comment]
@gabrielmocanu Docker version 23.0.1, build a5ee5b1dfc

**Comment by gabrielmocanu** [comment]
@danaxd  Do you have the same issue with the new version of Makefile?
It should be fixed now. Please pull the latest version.

**Comment by gabrielmocanu** [comment]
@danaxd 

I will close this issue since seems to be solved.
Please reopen it if you still have a problem with it.
